/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: s2.i

#define SWIGMODULE s2

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


#define SWIG_exception(code, msg) _swig_gopanic(msg)


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}


#include <string>


#include <vector>
#include <stdexcept>


#include <stdexcept>


#include <utility>


#include <list>
#include <stdexcept>


#include <map>
#include <algorithm>
#include <stdexcept>

SWIGINTERN std::vector< std::string >::const_reference std_vector_Sl_std_string_Sg__get(std::vector< std::string > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_string_Sg__set(std::vector< std::string > *self,int i,std::vector< std::string >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< char >::const_reference std_vector_Sl_char_Sg__get(std::vector< char > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_char_Sg__set(std::vector< char > *self,int i,std::vector< char >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }

#include "src/geometry/r1interval.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_s2_78f4f9645f0d9c42(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_0_s2_78f4f9645f0d9c42() {
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  
  result = (std::vector< std::string > *)new std::vector< std::string >();
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_1_s2_78f4f9645f0d9c42(long long _swig_go_0) {
  std::vector< std::string >::size_type arg1 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >(arg1);
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


long long _wrap_StringVector_size_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_StringVector_capacity_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_StringVector_reserve_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0, long long _swig_go_1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type arg2 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(arg2);
  
}


bool _wrap_StringVector_isEmpty_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (bool)((std::vector< std::string > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_StringVector_clear_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_StringVector_add_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  std::vector< std::string >::value_type arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  (arg1)->push_back((std::vector< std::string >::value_type const &)*arg2);
  
}


_gostring_ _wrap_StringVector_get_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0, intgo _swig_go_1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< std::string >::value_type *) &std_vector_Sl_std_string_Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_StringVector_set_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  std::vector< std::string >::value_type arg3_str(_swig_go_2.p, _swig_go_2.n);
  arg3 = &arg3_str;
  
  
  try {
    std_vector_Sl_std_string_Sg__set(arg1,arg2,(std::string const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
  
}


void _wrap_delete_StringVector_s2_78f4f9645f0d9c42(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_new_ByteVector__SWIG_0_s2_78f4f9645f0d9c42() {
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  
  result = (std::vector< char > *)new std::vector< char >();
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_new_ByteVector__SWIG_1_s2_78f4f9645f0d9c42(long long _swig_go_0) {
  std::vector< char >::size_type arg1 ;
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< char > *)new std::vector< char >(arg1);
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


long long _wrap_ByteVector_size_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = ((std::vector< char > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_ByteVector_capacity_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = ((std::vector< char > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ByteVector_reserve_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0, long long _swig_go_1) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::size_type arg2 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(arg2);
  
}


bool _wrap_ByteVector_isEmpty_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = (bool)((std::vector< char > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ByteVector_clear_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_ByteVector_add_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0, char _swig_go_1) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  std::vector< char >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (std::vector< char >::value_type *)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< char >::value_type const &)*arg2);
  
}


char _wrap_ByteVector_get_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0, intgo _swig_go_1) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  int arg2 ;
  std::vector< char >::value_type *result = 0 ;
  char _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< char >::value_type *) &std_vector_Sl_char_Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
  _swig_go_result = (char)*result; 
  return _swig_go_result;
}


void _wrap_ByteVector_set_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0, intgo _swig_go_1, char _swig_go_2) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  int arg2 ;
  std::vector< char >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (std::vector< char >::value_type *)&_swig_go_2; 
  
  try {
    std_vector_Sl_char_Sg__set(arg1,arg2,(char const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
  
}


void _wrap_delete_ByteVector_s2_78f4f9645f0d9c42(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = (std::vector< char > *) 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  delete arg1;
  
}


R1Interval *_wrap_new_R1Interval__SWIG_0_s2_78f4f9645f0d9c42(double _swig_go_0, double _swig_go_1) {
  double arg1 ;
  double arg2 ;
  R1Interval *result = 0 ;
  R1Interval *_swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = (R1Interval *)new R1Interval(arg1,arg2);
  *(R1Interval **)&_swig_go_result = (R1Interval *)result; 
  return _swig_go_result;
}


R1Interval *_wrap_new_R1Interval__SWIG_1_s2_78f4f9645f0d9c42() {
  R1Interval *result = 0 ;
  R1Interval *_swig_go_result;
  
  
  result = (R1Interval *)new R1Interval();
  *(R1Interval **)&_swig_go_result = (R1Interval *)result; 
  return _swig_go_result;
}


R1Interval *_wrap_R1Interval_Empty_s2_78f4f9645f0d9c42() {
  R1Interval result;
  R1Interval *_swig_go_result;
  
  
  result = R1Interval::Empty();
  *(R1Interval **)&_swig_go_result = new R1Interval(result); 
  return _swig_go_result;
}


R1Interval *_wrap_R1Interval_FromPoint_s2_78f4f9645f0d9c42(double _swig_go_0) {
  double arg1 ;
  R1Interval result;
  R1Interval *_swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  
  result = R1Interval::FromPoint(arg1);
  *(R1Interval **)&_swig_go_result = new R1Interval(result); 
  return _swig_go_result;
}


R1Interval *_wrap_R1Interval_FromPointPair_s2_78f4f9645f0d9c42(double _swig_go_0, double _swig_go_1) {
  double arg1 ;
  double arg2 ;
  R1Interval result;
  R1Interval *_swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = R1Interval::FromPointPair(arg1,arg2);
  *(R1Interval **)&_swig_go_result = new R1Interval(result); 
  return _swig_go_result;
}


double _wrap_R1Interval_lo_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  result = (double)((R1Interval const *)arg1)->lo();
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_R1Interval_hi_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  result = (double)((R1Interval const *)arg1)->hi();
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_R1Interval_bound_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, intgo _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  int arg2 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (double)((R1Interval const *)arg1)->bound(arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


Vector2_d *_wrap_R1Interval_bounds_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  Vector2_d *result = 0 ;
  Vector2_d *_swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  result = (Vector2_d *) &((R1Interval const *)arg1)->bounds();
  *(Vector2_d **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_R1Interval_set_lo_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, double _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double arg2 ;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  (arg1)->set_lo(arg2);
  
}


void _wrap_R1Interval_set_hi_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, double _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double arg2 ;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  (arg1)->set_hi(arg2);
  
}


bool _wrap_R1Interval_is_empty_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  result = (bool)((R1Interval const *)arg1)->is_empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_R1Interval_GetCenter_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  result = (double)((R1Interval const *)arg1)->GetCenter();
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_R1Interval_GetLength_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  result = (double)((R1Interval const *)arg1)->GetLength();
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_Contains__SWIG_0_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, double _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double arg2 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->Contains(arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_InteriorContains__SWIG_0_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, double _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double arg2 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->InteriorContains(arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_Contains__SWIG_1_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->Contains((R1Interval const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_InteriorContains__SWIG_1_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->InteriorContains((R1Interval const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_Intersects_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->Intersects((R1Interval const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_InteriorIntersects_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->InteriorIntersects((R1Interval const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_R1Interval_GetDirectedHausdorffDistance_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = (double)((R1Interval const *)arg1)->GetDirectedHausdorffDistance((R1Interval const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_R1Interval_AddPoint_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, double _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double arg2 ;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  (arg1)->AddPoint(arg2);
  
}


R1Interval *_wrap_R1Interval_Expanded_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, double _swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  double arg2 ;
  R1Interval result;
  R1Interval *_swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = ((R1Interval const *)arg1)->Expanded(arg2);
  *(R1Interval **)&_swig_go_result = new R1Interval(result); 
  return _swig_go_result;
}


R1Interval *_wrap_R1Interval_Union_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  R1Interval result;
  R1Interval *_swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = ((R1Interval const *)arg1)->Union((R1Interval const &)*arg2);
  *(R1Interval **)&_swig_go_result = new R1Interval(result); 
  return _swig_go_result;
}


R1Interval *_wrap_R1Interval_Intersection_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  R1Interval result;
  R1Interval *_swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = ((R1Interval const *)arg1)->Intersection((R1Interval const &)*arg2);
  *(R1Interval **)&_swig_go_result = new R1Interval(result); 
  return _swig_go_result;
}


bool _wrap_R1Interval_ApproxEquals__SWIG_0_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1, double _swig_go_2) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  double arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  arg3 = (double)_swig_go_2; 
  
  result = (bool)((R1Interval const *)arg1)->ApproxEquals((R1Interval const &)*arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_R1Interval_ApproxEquals__SWIG_1_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0, R1Interval *_swig_go_1) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  R1Interval *arg2 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  arg2 = *(R1Interval **)&_swig_go_1; 
  
  result = (bool)((R1Interval const *)arg1)->ApproxEquals((R1Interval const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_R1Interval_s2_78f4f9645f0d9c42(R1Interval *_swig_go_0) {
  R1Interval *arg1 = (R1Interval *) 0 ;
  
  arg1 = *(R1Interval **)&_swig_go_0; 
  
  delete arg1;
  
}


#ifdef __cplusplus
}
#endif

